INSERT INTO GENERATOR (GEN_NAME) VALUES ('CUSTOMER_GEN');
INSERT INTO GENERATOR (GEN_NAME) VALUES ('USER_ACCOUNT_GEN');
INSERT INTO GENERATOR (GEN_NAME) VALUES ('ROLE_GEN');
INSERT INTO GENERATOR (GEN_NAME) VALUES ('EINSTITUTION_GEN');
INSERT INTO GENERATOR (GEN_NAME) VALUES ('SPECIALITY_GEN');
INSERT INTO GENERATOR (GEN_NAME) VALUES ('ENROLLEE_GEN');
INSERT INTO GENERATOR (GEN_NAME) VALUES ('CERTIFICATE_GEN');
INSERT INTO GENERATOR (GEN_NAME) VALUES ('SUBJECT_GEN');
INSERT INTO GENERATOR (GEN_NAME) VALUES ('REGISTRATION_GEN');
INSERT INTO GENERATOR (GEN_NAME) VALUES ('REPORT_TEMPLATE_GEN');

INSERT INTO CUSTOMER (CUSTOMER_KEY, CUSTOMER_NAME) VALUES 
	((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'CUSTOMER_GEN'), 'Ð£Ðž "ÐœÐ Ðš"');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'CUSTOMER_GEN';

INSERT INTO USER_ACCOUNT (USER_ACCOUNT_KEY, USERNAME, CUSTOMER_KEY, FIRST_NAME, LAST_NAME, BIRTHDATE, EMAIL, ENABLED, PASSWORD)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'USER_ACCOUNT_GEN'), 'makseemka', (SELECT CUSTOMER_KEY FROM CUSTOMER WHERE CUSTOMER_NAME = 'Ð£Ðž "ÐœÐ Ðš"'), 'ÐœÐ°ÐºÑ�Ð¸Ð¼', 'Ð”Ñ€Ð°Ð³ÑƒÐ½', '1991-02-04', 'max@dragberry.net', true, '$2a$04$QjQ1pKIFt.KZMUD/ZjhWFOBBLYOshUh9OMIZ5y76t61A2mNV8qGSG');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'USER_ACCOUNT_GEN';
INSERT INTO USER_ACCOUNT (USER_ACCOUNT_KEY, USERNAME, CUSTOMER_KEY, FIRST_NAME, LAST_NAME, BIRTHDATE, EMAIL, ENABLED, PASSWORD)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'USER_ACCOUNT_GEN'), 'chueshkovu', (SELECT CUSTOMER_KEY FROM CUSTOMER WHERE CUSTOMER_NAME = 'Ð£Ðž "ÐœÐ Ðš"'), 'Ð®Ñ€Ð¸Ð¹', 'Ð§ÑƒÐµÑˆÐºÐ»Ð²', '1994-08-25', 'chueshkov@dragberry.net', true, '$2a$04$QjQ1pKIFt.KZMUD/ZjhWFOBBLYOshUh9OMIZ5y76t61A2mNV8qGSG');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'USER_ACCOUNT_GEN';

INSERT INTO ROLE (ROLE_KEY, ROLE_NAME)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'ROLE_GEN'), 'ADMIN');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'ROLE_GEN';
INSERT INTO ROLE (ROLE_KEY, ROLE_NAME)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'ROLE_GEN'), 'CUSTOMER_ADMIN');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'ROLE_GEN';
INSERT INTO ROLE (ROLE_KEY, ROLE_NAME)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'ROLE_GEN'), 'USER');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'ROLE_GEN';

INSERT INTO USER_ACCOUNT_ROLE (USER_ACCOUNT_KEY, ROLE_KEY) 
	VALUES (
		(SELECT USER_ACCOUNT_KEY FROM USER_ACCOUNT WHERE USERNAME = 'makseemka'), 
		(SELECT ROLE_KEY FROM ROLE WHERE ROLE_NAME = 'ADMIN'));
INSERT INTO USER_ACCOUNT_ROLE (USER_ACCOUNT_KEY, ROLE_KEY) 
	VALUES (
		(SELECT USER_ACCOUNT_KEY FROM USER_ACCOUNT WHERE USERNAME = 'makseemka'), 
		(SELECT ROLE_KEY FROM ROLE WHERE ROLE_NAME = 'CUSTOMER_ADMIN'));
INSERT INTO USER_ACCOUNT_ROLE (USER_ACCOUNT_KEY, ROLE_KEY) 
	VALUES (
		(SELECT USER_ACCOUNT_KEY FROM USER_ACCOUNT WHERE USERNAME = 'makseemka'), 
		(SELECT ROLE_KEY FROM ROLE WHERE ROLE_NAME = 'USER'));
INSERT INTO USER_ACCOUNT_ROLE (USER_ACCOUNT_KEY, ROLE_KEY) 
	VALUES (
		(SELECT USER_ACCOUNT_KEY FROM USER_ACCOUNT WHERE USERNAME = 'chueshkovu'), 
		(SELECT ROLE_KEY FROM ROLE WHERE ROLE_NAME = 'USER'));

INSERT INTO EDUCATION_INSTITUTION (EDUCATION_INSTITUTION_KEY, NAME, SHORT_NAME, COUNTRY, CITY)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'EINSTITUTION_GEN'), 'Ð¤Ð¸Ð»Ð¸Ð°Ð» Ð‘Ð“Ð£Ð˜Ð  "ÐœÐ¸Ð½Ñ�ÐºÐ¸Ð¹ Ñ€Ð°Ð´Ð¸Ð¾Ñ‚ÐµÑ…Ð½Ð¸Ñ‡ÐµÑ�ÐºÐ¸Ð¹ ÐºÐ¾Ð»Ð»ÐµÐ´Ð¶"', 'Ð£Ðž "ÐœÐ Ðš"', 'BY', 'ÐœÐ¸Ð½Ñ�Ðº');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'EINSTITUTION_GEN';

INSERT INTO SPECIALITY (SPECIALITY_KEY, CODE, TITLE, STATUS)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'SPECIALITY_GEN'), '2 39 02 32', 'ÐŸÑ€Ð¾ÐµÐºÑ‚Ð¸Ñ€Ð¾Ð²Ð°Ð½Ð¸Ðµ Ð¸ Ð¿Ñ€Ð¾Ð¸Ð·Ð²Ð¾Ð´Ñ�Ñ‚Ð²Ð¾ Ñ€Ð°Ð´Ð¸Ð¾Ñ�Ð»ÐµÐºÑ‚Ñ€Ð¾Ð½Ð½Ñ‹Ñ… Ñ�Ñ€ÐµÐ´Ñ�Ñ‚Ð²', 'A');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'SPECIALITY_GEN';
INSERT INTO SPECIALITY (SPECIALITY_KEY, CODE, TITLE, STATUS)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'SPECIALITY_GEN'), '2 39 02 31', 'Ð¢ÐµÑ…Ð½Ð¸Ñ‡ÐµÑ�ÐºÐ°Ñ� Ñ�ÐºÑ�Ð¿Ð»ÑƒÐ°Ñ‚Ð°Ñ†Ð¸Ñ� Ñ€Ð°Ð´Ð¸Ð¾Ñ�Ð»ÐµÐºÑ‚Ñ€Ð¾Ð½Ð½Ñ‹Ñ… Ñ�Ñ€ÐµÐ´Ñ�Ñ‚Ð²', 'A');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'SPECIALITY_GEN';
INSERT INTO SPECIALITY (SPECIALITY_KEY, CODE, TITLE, STATUS)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'SPECIALITY_GEN'), '2 40 02 02', 'Ð­Ð»ÐµÐºÑ‚Ñ€Ð¾Ð½Ð½Ñ‹Ðµ Ð²Ñ‹Ñ‡Ð¸Ñ�Ð»Ð¸Ñ‚ÐµÐ»ÑŒÐ½Ñ‹Ðµ Ñ�Ñ€ÐµÐ´Ñ�Ñ‚Ð²Ð°', 'A');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'SPECIALITY_GEN';
INSERT INTO SPECIALITY (SPECIALITY_KEY, CODE, TITLE, STATUS)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'SPECIALITY_GEN'), '2 41 01 02', 'ÐœÐ¸ÐºÑ€Ð¾- Ð¸ Ð½Ð°Ð½Ð¾Ñ�Ð»ÐµÐºÑ‚Ñ€Ð¾Ð½Ð½Ñ‹Ðµ Ñ‚ÐµÑ…Ð½Ð¾Ð»Ð¾Ð³Ð¸Ð¸ Ð¸ Ñ�Ð¸Ñ�Ñ‚ÐµÐ¼Ñ‹', 'A');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'SPECIALITY_GEN';
INSERT INTO SPECIALITY (SPECIALITY_KEY, CODE, TITLE, STATUS)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'SPECIALITY_GEN'), '2 40 01 01', 'ÐŸÑ€Ð¾Ð³Ñ€Ð°Ð¼Ð¼Ð½Ð¾Ðµ Ð¾Ð±ÐµÑ�Ð¿ÐµÑ‡ÐµÐ½Ð¸Ðµ Ð¸Ð½Ñ„Ð¾Ñ€Ð¼Ð°Ñ†Ð¸Ð¾Ð½Ð½Ñ‹Ñ… Ñ‚ÐµÑ…Ð½Ð¾Ð»Ð¾Ð³Ð¸Ð¹', 'A');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'SPECIALITY_GEN';
INSERT INTO SPECIALITY (SPECIALITY_KEY, CODE, TITLE, STATUS)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'SPECIALITY_GEN'), '2 39 03 02', 'ÐŸÑ€Ð¾Ð³Ñ€Ð°Ð¼Ð¼Ð¸Ñ€ÑƒÐµÐ¼Ñ‹Ðµ Ð¼Ð¾Ð±Ð¸Ð»ÑŒÐ½Ñ‹Ðµ Ñ�Ð¸Ñ�Ñ‚ÐµÐ¼Ñ‹', 'A');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'SPECIALITY_GEN';

INSERT INTO EINSTITUTION_SPECIALITY (EDUCATION_INSTITUTION_KEY, SPECIALITY_KEY) 
	SELECT EI.EDUCATION_INSTITUTION_KEY, S.SPECIALITY_KEY 
		FROM EDUCATION_INSTITUTION EI, SPECIALITY S
		WHERE EI.NAME = 'Ð¤Ð¸Ð»Ð¸Ð°Ð» Ð‘Ð“Ð£Ð˜Ð  "ÐœÐ¸Ð½Ñ�ÐºÐ¸Ð¹ Ñ€Ð°Ð´Ð¸Ð¾Ñ‚ÐµÑ…Ð½Ð¸Ñ‡ÐµÑ�ÐºÐ¸Ð¹ ÐºÐ¾Ð»Ð»ÐµÐ´Ð¶"' 
		AND S.CODE IN ('2 39 02 32', '2 39 02 31', '2 40 02 02', '2 41 01 02', '2 40 01 01', '2 39 03 02');
		
INSERT INTO SUBJECT (SUBJECT_KEY, TITLE)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'SUBJECT_GEN'), 'Ð ÑƒÑ�Ñ�ÐºÐ¸Ð¹ Ñ�Ð·Ñ‹Ðº');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'SUBJECT_GEN';
INSERT INTO SUBJECT (SUBJECT_KEY, TITLE)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'SUBJECT_GEN'), 'Ð ÑƒÑ�Ñ�ÐºÐ°Ñ� Ð»Ð¸Ñ‚ÐµÑ€Ð°Ñ‚ÑƒÑ€Ð°');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'SUBJECT_GEN';
INSERT INTO SUBJECT (SUBJECT_KEY, TITLE)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'SUBJECT_GEN'), 'Ð‘ÐµÐ»Ð¾Ñ€ÑƒÑ�Ñ�ÐºÐ¸Ð¹ Ñ�Ð·Ñ‹Ðº');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'SUBJECT_GEN';
INSERT INTO SUBJECT (SUBJECT_KEY, TITLE)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'SUBJECT_GEN'), 'Ð‘ÐµÐ»Ð¾Ñ€ÑƒÑ�Ñ�ÐºÐ°Ñ� Ð»Ð¸Ñ‚ÐµÑ€Ð°Ñ‚ÑƒÑ€Ð°');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'SUBJECT_GEN';
INSERT INTO SUBJECT (SUBJECT_KEY, TITLE)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'SUBJECT_GEN'), 'ÐœÐ°Ñ‚ÐµÐ¼Ð°Ñ‚Ð¸ÐºÐ°');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'SUBJECT_GEN';
INSERT INTO SUBJECT (SUBJECT_KEY, TITLE)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'SUBJECT_GEN'), 'Ð¥Ð¸Ð¼Ð¸Ñ�');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'SUBJECT_GEN';
INSERT INTO SUBJECT (SUBJECT_KEY, TITLE)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'SUBJECT_GEN'), 'Ð¤Ð¸Ð·Ð¸ÐºÐ°');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'SUBJECT_GEN';
INSERT INTO SUBJECT (SUBJECT_KEY, TITLE)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'SUBJECT_GEN'), 'Ð‘Ð¸Ð¾Ð»Ð¾Ð³Ð¸Ñ�');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'SUBJECT_GEN';