INSERT INTO BENEFIT 
	(BENEFIT_KEY, PRIORITY, TYPE, DELETED, NAME, DESCRIPTION)
VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'BENEFIT_GEN'),
		0, 'O', 0, 'Сирота', '');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'BENEFIT_GEN';
