INSERT INTO PREROGATIVE 
	(PREROGATIVE_KEY, PRIORITY, DELETED, NAME, DESCRIPTION)
VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'PREROGATIVE_GEN'),
		0, 0, 'Инвалиды I и II групп', '');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'PREROGATIVE_GEN';

INSERT INTO PREROGATIVE 
	(PREROGATIVE_KEY, PRIORITY, DELETED, NAME, DESCRIPTION)
VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'PREROGATIVE_GEN'),
		1, 0, 'Дети военнослужащих (умерших или инвалидов)', '');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'PREROGATIVE_GEN';

INSERT INTO PREROGATIVE 
	(PREROGATIVE_KEY, PRIORITY, DELETED, NAME, DESCRIPTION)
VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'PREROGATIVE_GEN'),
		2, 0, 'Суворовцы', '');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'PREROGATIVE_GEN';

INSERT INTO PREROGATIVE 
	(PREROGATIVE_KEY, PRIORITY, DELETED, NAME, DESCRIPTION)
VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'PREROGATIVE_GEN'),
		3, 0, 'ЧАЭС (ст. 18)', '');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'PREROGATIVE_GEN';

INSERT INTO PREROGATIVE 
	(PREROGATIVE_KEY, PRIORITY, DELETED, NAME, DESCRIPTION)
VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'PREROGATIVE_GEN'),
		4, 0, 'Инвалиды III группы', '');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'PREROGATIVE_GEN';

INSERT INTO PREROGATIVE 
	(PREROGATIVE_KEY, PRIORITY, DELETED, NAME, DESCRIPTION)
VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'PREROGATIVE_GEN'),
		5, 0, 'ЧАЭС (ст. 19-23)', '');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'PREROGATIVE_GEN';


INSERT INTO PREROGATIVE 
	(PREROGATIVE_KEY, PRIORITY, DELETED, NAME, DESCRIPTION)
VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'PREROGATIVE_GEN'),
		6, 0, 'Многотетная семья', '');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'PREROGATIVE_GEN';
