-- Admin roles
INSERT INTO ROLE (ROLE_KEY, MODULE, ACTION)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'ROLE_GEN'), 'ADMIN', 'VIEW');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'ROLE_GEN';
-- Registrations roles
INSERT INTO ROLE (ROLE_KEY, MODULE, ACTION)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'ROLE_GEN'), 'REGISTRATIONS', 'VIEW');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'ROLE_GEN';
INSERT INTO ROLE (ROLE_KEY, MODULE, ACTION)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'ROLE_GEN'), 'REGISTRATIONS', 'CREATE');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'ROLE_GEN';
INSERT INTO ROLE (ROLE_KEY, MODULE, ACTION)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'ROLE_GEN'), 'REGISTRATIONS', 'UPDATE');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'ROLE_GEN';
INSERT INTO ROLE (ROLE_KEY, MODULE, ACTION)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'ROLE_GEN'), 'REGISTRATIONS', 'DELETE');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'ROLE_GEN';
-- User accounts roles
INSERT INTO ROLE (ROLE_KEY, MODULE, ACTION)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'ROLE_GEN'), 'USERACCOUNTS', 'VIEW');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'ROLE_GEN';
INSERT INTO ROLE (ROLE_KEY, MODULE, ACTION)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'ROLE_GEN'), 'USERACCOUNTS', 'CREATE');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'ROLE_GEN';
INSERT INTO ROLE (ROLE_KEY, MODULE, ACTION)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'ROLE_GEN'), 'USERACCOUNTS', 'UPDATE');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'ROLE_GEN';
INSERT INTO ROLE (ROLE_KEY, MODULE, ACTION)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'ROLE_GEN'), 'USERACCOUNTS', 'DELETE');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'ROLE_GEN';
