INSERT INTO EXAM_SUBJECT (EXAM_SUBJECT_KEY, CODE, TITLE)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'EXAM_SUBJECT_GEN'), '01', 'Русский язык');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'EXAM_SUBJECT_GEN';
INSERT INTO EXAM_SUBJECT (EXAM_SUBJECT_KEY, CODE, TITLE)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'EXAM_SUBJECT_GEN'), '02', 'Белорусский язык');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'EXAM_SUBJECT_GEN';
INSERT INTO EXAM_SUBJECT (EXAM_SUBJECT_KEY, CODE, TITLE)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'EXAM_SUBJECT_GEN'), '03', 'Физика');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'EXAM_SUBJECT_GEN';
INSERT INTO EXAM_SUBJECT (EXAM_SUBJECT_KEY, CODE, TITLE)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'EXAM_SUBJECT_GEN'), '04', 'Математика');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'EXAM_SUBJECT_GEN';
INSERT INTO EXAM_SUBJECT (EXAM_SUBJECT_KEY, CODE, TITLE)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'EXAM_SUBJECT_GEN'), '05', 'Химия');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'EXAM_SUBJECT_GEN';
INSERT INTO EXAM_SUBJECT (EXAM_SUBJECT_KEY, CODE, TITLE)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'EXAM_SUBJECT_GEN'), '06', 'Биология');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'EXAM_SUBJECT_GEN';
INSERT INTO EXAM_SUBJECT (EXAM_SUBJECT_KEY, CODE, TITLE)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'EXAM_SUBJECT_GEN'), '07', 'Английский язык');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'EXAM_SUBJECT_GEN';
INSERT INTO EXAM_SUBJECT (EXAM_SUBJECT_KEY, CODE, TITLE)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'EXAM_SUBJECT_GEN'), '08', 'Немецкий язык');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'EXAM_SUBJECT_GEN';
INSERT INTO EXAM_SUBJECT (EXAM_SUBJECT_KEY, CODE, TITLE)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'EXAM_SUBJECT_GEN'), '09', 'Французский язык');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'EXAM_SUBJECT_GEN';
INSERT INTO EXAM_SUBJECT (EXAM_SUBJECT_KEY, CODE, TITLE)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'EXAM_SUBJECT_GEN'), '10', 'Испанский язык');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'EXAM_SUBJECT_GEN';
INSERT INTO EXAM_SUBJECT (EXAM_SUBJECT_KEY, CODE, TITLE)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'EXAM_SUBJECT_GEN'), '11', 'Китайский язык');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'EXAM_SUBJECT_GEN';
INSERT INTO EXAM_SUBJECT (EXAM_SUBJECT_KEY, CODE, TITLE)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'EXAM_SUBJECT_GEN'), '12', 'Истоия Беларуси');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'EXAM_SUBJECT_GEN';
INSERT INTO EXAM_SUBJECT (EXAM_SUBJECT_KEY, CODE, TITLE)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'EXAM_SUBJECT_GEN'), '13', 'Обществоведение');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'EXAM_SUBJECT_GEN';
INSERT INTO EXAM_SUBJECT (EXAM_SUBJECT_KEY, CODE, TITLE)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'EXAM_SUBJECT_GEN'), '14', 'География');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'EXAM_SUBJECT_GEN';
INSERT INTO EXAM_SUBJECT (EXAM_SUBJECT_KEY, CODE, TITLE)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'EXAM_SUBJECT_GEN'), '15', 'Всемирная история');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'EXAM_SUBJECT_GEN';